name: Build & Deploy
on:
  push:
    branches:
      - "main"
      - "init_ci"
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/subtask-build.yaml
    with:
      package: true
  deploy:
    needs: [build]
    strategy:
      matrix:
        environment: [prod]
    uses: ./.github/workflows/subtask-deploy.yaml
    with:
      environment: ${{matrix.environment}}
    secrets: inherit
