name: Build (Sub-Task)
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: boolean
jobs:
  build-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.x
      # - name: Install Dependencies
      #   run: npm ci
      #   working-directory: workers/b2-proxy
      - name: Zip Worker
        id: zip-b2-proxy
        if: ${{inputs.package}}
        run: |
          workingDirectory=$(pwd)
          cd ./workers/b2-proxy

          zipFile=artifact.zip
          zip -r $zipFile .

          outputDirectory=$workingDirectory/artifacts
          outputFile=$outputDirectory/$zipFile
          mkdir -p $workingDirectory
          cp ./$zipFile $outputFile

          echo 'artifact<<EOF' >> $GITHUB_OUTPUT
          echo $outputFile >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Upload Worker
        if: github.event.inputs.package
        uses: actions/upload-artifact@v4
        with:
          name: B2-Worker
          path: ${{steps.zip-b2-proxy.outputs.artifact}}
